ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.SerializationKt.configureSerialization
      - com.example.StatusPagesKt.configureStatusPages
      - com.example.CorsKt.configureCors
      - com.example.config.AuthenticationConfigKt.configureAuthentication
      - com.example.RoutingKt.configureRouting
